services:
  postgres:
    image: postgres:15
    container_name: postgres
    networks:
      - dataplatform
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - "/home/vanhcao/vietanh/graduation project/data.sql:/docker-entrypoint-initdb.d/data.sql"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    networks:
      - dataplatform
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    networks:
      - dataplatform
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - dataplatform
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  nifi:
    image: apache/nifi:1.23.2
    container_name: nifi
    networks:
      - dataplatform
    ports:
      - "8443:8443"
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: adminadminadmin
    volumes:
      - ./nifi/flow:/opt/nifi/nifi-current/flow
      - ./nifi/logs:/opt/nifi/nifi-current/logs
    depends_on:
      - kafka
      - postgres

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    networks:
      - dataplatform
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      CLUSTER_NAME: local-cluster
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    volumes:
      - ./hdfs/namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    networks:
      - dataplatform
    depends_on:
      - namenode
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      SERVICE_PRECONDITION: "namenode:9870"
    volumes:
      - ./hdfs/datanode:/hadoop/dfs/data

  spark-master:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-master
    networks:
      - dataplatform
    ports:
      - "8090:8080"
      - "7077:7077"
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      SPARK_RPC_ENCRYPTION_ENABLED: "no"

  spark-worker:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-worker
    networks:
      - dataplatform
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2

  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   networks:
  #     - dataplatform
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_models:/root/.ollama
  #   environment:
  #     - OLLAMA_HOST=0.0.0.0

  ai-agent:
    build:
      context: ./ai-agent
      dockerfile: Dockerfile
    container_name: ai-agent
    networks:
      - dataplatform
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ecommerce
      DB_USER: postgres
      DB_PASSWORD: postgres
      OLLAMA_HOST: http://ollama:11434
    depends_on:
      - postgres
      # - ollama

  data-source:
    build:
      context: ./data-source
      dockerfile: Dockerfile
    container_name: data-source
    networks:
      - dataplatform
    env_file:
      - ./.env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    working_dir: /app
    volumes:
      - ./data-source:/app
    depends_on:
      - postgres
      - kafka
    command: sleep infinity

networks:
  dataplatform:
    driver: bridge

volumes:
  ollama_models: